import type { Metadata } from "next";
import "./globals.css"; // এখানে তুমি fonts.css ইমপোর্ট করবে

export const metadata: Metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-[#191D29] font-tttravels">
        {children}
      </body>
    </html>
  );
}
